### ISSUE TITLE
How to selfhost plugin?

### ISSUE THREAD

**Issue by alexkutsan** [RdeLange/nomie-plugin-api#1]
I was trying to set up plugin using https://dailynomie.github.io/nomie-plugin-api/ 
Then I setup the API server on the same domain and my nomie with but with prefix `/ui` : https://github.com/RdeLange/nomie-server-api

But when I am trying to setup the API server - I catch CORS issue in the browser as soon as the plugin origin: dailynomie.github.io does not match the domain of my server. 

![изображение](https://user-images.githubusercontent.com/860357/226113835-a8bf847a-1155-4434-b552-b49057b975c2.png)

Soluiton would be to store the plugin itself on my domain, but how can I do it?

**Comment by RdeLange** [comment]
I need to have some more info to validate where the problem lies, so I have some questions:

- you installed the plugin via https://dailynomie.github.io/nomie-plugin-api/ => correct?

Then I am wondering how you installed the api server:
- did you install via docker? 
- did you use an existing docker image like https://hub.docker.com/repository/docker/rdelange/dailynomie-apiserver/general ?
- or did you setup another way?

**Comment by alexkutsan** [comment]
> you installed the plugin via https://dailynomie.github.io/nomie-plugin-api/ => correct?
Yes
I use docker compose for nomie, CouchDB and API nomie API:

```
version: '3.1'
services:
  nomie6:
    image: ghcr.io/qcasey/nomie6-oss:master
    restart: unless-stopped
    ports:
      - ${INTERNAL_IP}:18572:80

  nomieapiserver:
    image: rdelange/dailynomie-apiserver:latest
    container_name: dailynomie-apiserver-docker
    volumes:
    - ./nomieapiserver_data:/home
    ports:
        - "${INTERNAL_IP}:1440:1880"

  couchdb:
    image: couchdb:3
    restart: unless-stopped
    ports:
      - ${INTERNAL_IP}:5984:5984
    environment:
      - NODENAME=couchdb
      - COUCHDB_USER=${COUCH_DB_USER}
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
    volumes:
      - ./data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.d/docker.ini
```

Then I have nginx configuration to access my nomie, CouchDB, and nomie API server: 
```
server {
  set $forward_scheme http;
  set $server         "INTERNAL_IP";
  set $port           1440;
  server_name wellness.alexkutsan.me;
  location /nomie_db {
    proxy_pass       http://100.106.66.60:5984;
  }
  location /ui {
    proxy_pass       http://100.106.66.60:1440;
  }
}
```

I was trying to setup nomie API server to separate domain, but I receive CORS issue as well, the same CORS issue, when I try to use api.dailynomie.com as nomie API server 

![изображение](https://user-images.githubusercontent.com/860357/226175757-2e03621b-efd6-4d2e-829b-1f737edf6a8a.png)

I am pretty sure, that if I host a plugin on my domain - the CORS issue should be gone, but I don't know how can I host plugin.

**Comment by alexkutsan** [comment]
I was trying to create dockerfile for this repo:

```
FROM node:14-alpine
WORKDIR /app
COPY . /app
RUN npm install
EXPOSE 5000
ENV NODE_ENV=production
CMD ["npm", "start", "--host", "0.0.0.0"]
```
But it still listening on localhost :
```

  Your application is ready~! 🚀

  - Local:      http://localhost:5000
  - Network:    Add `--host` to expose

────────────────── LOGS ──────────────────
```
And I can't reach it by external IP

**Comment by RdeLange** [comment]
Hi,

I have create an docker image for the plugin:
ghcr.io/rdelange/nomie-plugin-api:main

it exposes port 5000.

Can you try using this image, running on your own domain?
You can then install the plugin in Nomie by giving the webaddress to the docker container.

I am curious if this will indeed solve the problem.

Regards,
Ronald

**Comment by alexkutsan** [comment]
Added to compose:
```
  nomie_api_plugin:
    image: ghcr.io/rdelange/nomie-plugin-api:main
    ports:
      - 100.106.66.60:5000:5000
```

But the plugin is not full loaded  :
![изображение](https://user-images.githubusercontent.com/860357/226211047-745d149f-fb33-4922-987d-153c0dc0a0d5.png)
